# Libraries

In [50]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [51]:
import pandas as pd
import json
import fs
import re

In [52]:
PROCESSED_FILES_DIR = fs.open_fs("../../data/processed")
PROCESSED_COMMENTS_COMBINED_DIR = PROCESSED_FILES_DIR.getsyspath("Combined.csv")
PROCESSED_COMMENTS_REPLIES_DIR = PROCESSED_FILES_DIR.getsyspath("Replies.csv")
PROCESSED_COMMENTS_ITEMS_DIR = PROCESSED_FILES_DIR.getsyspath("Items.csv")

In [53]:
df_items = pd.read_csv(PROCESSED_COMMENTS_ITEMS_DIR)
# df_combined = pd.read_csv(PROCESSED_COMMENTS_ITEMS_DIR)
# df_replies = pd.read_csv(PROCESSED_COMMENTS_ITEMS_DIR)

In [54]:
df_items

,kind,etag,id,snippet.channelId,snippet.videoId,snippet.topLevelComment.kind,snippet.topLevelComment.etag,snippet.topLevelComment.id,snippet.topLevelComment.snippet.channelId,snippet.topLevelComment.snippet.videoId,...,snippet.topLevelComment.snippet.authorChannelId.value,snippet.topLevelComment.snippet.canRate,snippet.topLevelComment.snippet.viewerRating,snippet.topLevelComment.snippet.likeCount,snippet.topLevelComment.snippet.publishedAt,snippet.topLevelComment.snippet.updatedAt,snippet.canReply,snippet.totalReplyCount,snippet.isPublic,replies.comments
0,youtube#commentThread,35SzVbfAjbh-WxxI6CDcz8jJalE,Ugz0QmXyVLSM0nUK7kB4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,youtube#comment,yopv5G2xkuk2ZN4mdQMDcEtKmS4,Ugz0QmXyVLSM0nUK7kB4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,...,UC3In6JIjltN9q3vYip-nhbA,True,none,0,2024-07-15T12:41:43Z,2024-07-15T12:41:43Z,True,0,True,NaN
1,youtube#commentThread,D5l-LBB9fD-VlBImz-EN9K8mTmM,UgyJhRBhVcbyStZdxjR4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,youtube#comment,avm1UM6tZkxbnMkp59t7_36GZrk,UgyJhRBhVcbyStZdxjR4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,...,UCbDEMBgOeP90oPLWs7-FDvQ,True,none,0,2024-05-26T21:41:04Z,2024-05-26T21:41:04Z,True,0,True,NaN
2,youtube#commentThread,iKN6FQSPLo3xUlizd--6R0h2SN8,UgzT1q2am7kMEM5ckDp4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,youtube#comment,g6vw71KL8rJyQPLYPCUCm4O6rbA,UgzT1q2am7kMEM5ckDp4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,...,UCPfzEUeII0UXFcf2t01dClA,True,none,0,2024-05-23T22:06:21Z,2024-05-23T22:06:21Z,True,0,True,NaN
3,youtube#commentThread,hkErqy7RZOwAKS6YyNXqwPFTCAg,Ugyckucg38lqZFdZhaR4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,youtube#comment,soQFV-F5m7bRA03fMjI1IoKQrGs,Ugyckucg38lqZFdZhaR4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,...,UCwfZIbgLOHYsNdWFfiMmfHg,True,none,0,2024-05-05T09:24:57Z,2024-05-05T09:24:57Z,True,0,True,NaN
4,youtube#commentThread,9c50dNDxQ96ZYyFK1aeJYj4ofnQ,UgzhZHVt-tEbDpbCvtB4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,youtube#comment,wLebngIiKaOrIw1ibNjosSTEyFc,UgzhZHVt-tEbDpbCvtB4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,cQ9RLDhq6JY,...,UC_aIjI_NTlEUd_zFkmTcpJQ,True,none,0,2024-04-21T21:09:08Z,2024-04-21T21:09:08Z,True,0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,youtube#commentThread,8wSxk2QdKgz2v0AUy3EsWvUOxSU,Ugyuq-tSoKFj7HEnAQ54AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,youtube#comment,G_pL0x_Nmvi7C0kj8fHi_IWkcCA,Ugyuq-tSoKFj7HEnAQ54AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,...,UCEDVPkLmXatD3pPEmukHDmw,True,none,0,2024-08-19T19:46:46Z,2024-08-19T19:46:46Z,True,0,True,NaN
1022,youtube#commentThread,X4xqkZX0x2OmHUMWh4fe2ck4iGA,Ugy2h_vD89gf_8eeFph4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,youtube#comment,fWBX1bGUjpM7nRaQcNKN1P7BpFQ,Ugy2h_vD89gf_8eeFph4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,...,UCbTyK6oHehb5LiFiA_DUfQQ,True,none,0,2024-08-19T19:33:41Z,2024-08-19T19:33:41Z,True,0,True,NaN
1023,youtube#commentThread,btoZQh1KTx4_A0e8kLI3d4BAUmg,Ugx7vBivUc-z-n8H76t4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,youtube#comment,CcywvY3FEol-BcpzJpjundijK6k,Ugx7vBivUc-z-n8H76t4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,...,UCzyaecofs2BCd6bI1BqqBWA,True,none,1,2024-08-19T19:33:18Z,2024-08-19T19:33:18Z,True,0,True,NaN
1024,youtube#commentThread,Xf-HPCYvwS0mb7JyqR4t_eoHZx4,Ugzvu7xFsIUo8ibNXPJ4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,youtube#comment,FLjbXmI4uIIbM1ZQNW-hMSKWARM,Ugzvu7xFsIUo8ibNXPJ4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,...,UCxu2psJcT48v7iCtU-YS3KA,True,none,0,2024-08-19T19:13:00Z,2024-08-19T19:13:00Z,True,0,True,NaN
1025,youtube#commentThread,OBq15WOOkVZGkZnpWOHgG9R_IwA,Ugx6mGMWrp3CU7o7Lwd4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,youtube#comment,yv8yKkXG4JYnco8VDd5FE9AWIto,Ugx6mGMWrp3CU7o7Lwd4AaABAg,UCeYSnd34IPe57sM8hkjWhrw,t3MogAmkMUg,...,UCRKEMLsie7vd42rN8EjxNTw,True,none,0,2024-08-19T18:55:54Z,2024-08-19T18:55:54Z,True,0,True,NaN

In [55]:
df_items["snippet.videoId"].value_counts()

snippet.videoId
RBnZPFhDcnk    83
ShW6FY-vbmo    59
FOFeh_vfcD8    59
qSjSUN6Rxhk    57
PAFwYBqf_Os    56
CPCN1Lqzc2U    55
QO_mORdhchw    50
J5dH-jKp-ac    50
yFHCam_Q9j4    49
FXxcNjTZ4qo    48
rx108V8Ydtc    45
t3MogAmkMUg    44
HxMXLWqe9HQ    42
0IDFrBktWIA    40
cOxTBBHDN-0    37
o7l_d75l-eo    34
5Uac-LKCY4Y    27
Vhf-VeTykO8    26
0kY6Qt1V8Kc    26
cQ9RLDhq6JY    26
7Jo3NR5lgd8    25
rXd-HsVezzs    24
kSRLcVrXYSY    23
Go2KlhN4cQk    22
wCm4FNSnDPs    19
Name: count, dtype: int64

In [56]:
df_ = df_items[df_items["snippet.videoId"] == "7Jo3NR5lgd8"]
df_c = df_[["snippet.topLevelComment.snippet.textDisplay", "snippet.topLevelComment.snippet.likeCount"]].sort_values(by="snippet.topLevelComment.snippet.likeCount", ascending=False)
df_c

,snippet.topLevelComment.snippet.textDisplay,snippet.topLevelComment.snippet.likeCount
768,"Voy a investigar el conflicto de myanmar, ahor...",15
760,"Hola, yo los escucho en Amazon music, desde qu...",9
759,🇯🇴 🫶🏻,5
758,Palestina libre 🇯🇴,4
762,El episodio más esperado por toda Latinoaméric...,3
761,A mí sí me gustan las pasas😂!!!!!,3
756,Siento que chile es el país que se menciona pa...,3
763,"Los árabes no eran dueños de esa región, así q...",2
769,Loviu chicos ✨ ya estaba esperando la continua...,2
770,Buenas un saludo para cuando hablan de la mito...,2
771,SIuuuuuu,2
750,Yo todos los capítulos de usteds los escucho e...,1
766,El 7 de octubre del 2023 no se olvidará VIVA I...,1
751,Considero que se debió platicar con poco más d...,0
749,Ah perros 🤟,0
748,espero cuenten como una fuente de consulta val...,0
747,"<a href=""https://www.youtube.com/watch?v=7Jo3N...",0
755,auto determinacion de los pueblos y putin si c...,0
754,Medio culebrón. Ya me perdí. Están todos locos...,0
753,Free Palestine 🇵🇸,0
752,Yo estoy firme en que no estoy de acuerdo con ...,0
757,Mi comentario antes de ver el podcast: El ataq...,0
767,ISRAEL ES SOBERANO YO COMO MEXICANO APOYO A IS...,0
764,Algo que me llama la atención es que en Palest...,0
765,Seles olvida las mujeres violad@s por hamas fu...,0