# Libraries

In [1]:
%load_ext autoreload
%autoreload 2

In [22]:
import scripts.yt_utils as yt_utils
import pandas as pd
import json
import fs

In [3]:
INTERIM_VIDEO_COMMETS_DIR = fs.open_fs("../../data/interim/video_commets")
csv_files = [file for file in INTERIM_VIDEO_COMMETS_DIR.listdir('/') if file.endswith('.csv')]
csv_files

['video_FOFeh_vfcD8_commets.csv',
 'video_0kY6Qt1V8Kc_commets.csv',
 'video_Vhf-VeTykO8_commets.csv',
 'video_o7l_d75l-eo_commets.csv',
 'video_qSjSUN6Rxhk_commets.csv',
 'video_cOxTBBHDN-0_commets.csv',
 'video_Go2KlhN4cQk_commets.csv',
 'video_0IDFrBktWIA_commets.csv',
 'video_5Uac-LKCY4Y_commets.csv',
 'video_kSRLcVrXYSY_commets.csv',
 'video_HxMXLWqe9HQ_commets.csv',
 'video_yFHCam_Q9j4_commets.csv',
 'video_rx108V8Ydtc_commets.csv',
 'video_QO_mORdhchw_commets.csv',
 'video_wCm4FNSnDPs_commets.csv',
 'video_7Jo3NR5lgd8_commets.csv',
 'video_rXd-HsVezzs_commets.csv',
 'video_FXxcNjTZ4qo_commets.csv',
 'video_ShW6FY-vbmo_commets.csv',
 'video_cQ9RLDhq6JY_commets.csv',
 'video_PAFwYBqf_Os_commets.csv',
 'video_RBnZPFhDcnk_commets.csv',
 'video_CPCN1Lqzc2U_commets.csv',
 'video_J5dH-jKp-ac_commets.csv',
 'video_t3MogAmkMUg_commets.csv']

In [7]:
DIR_CSV = INTERIM_VIDEO_COMMETS_DIR.getsyspath(csv_files[0])

In [9]:
df = pd.read_csv(DIR_CSV)
df.head()

,channelId,videoId,commentId,textDisplay,textOriginal,authorDisplayName,authorProfileImageUrl,authorChannelUrl,authorChannelId,canRate,viewerRating,likeCount,publishedAt,updatedAt,canReply,totalReplyCount,isPublic,replies
0,UCeYSnd34IPe57sM8hkjWhrw,FOFeh_vfcD8,NaN,Hagan un episodio sobre la defenza de boqueron...,Hagan un episodio sobre la defenza de boqueron...,@warrobotsdon-roro2537,https://yt3.ggpht.com/ytc/AIdro_kNz_6aT-NycY4q...,http://www.youtube.com/@warrobotsdon-roro2537,UCPfpPCYyrAKGS11NqvWMuqw,True,none,0,2024-07-29T11:59:40Z,2024-07-29T11:59:40Z,True,0,True,{}
1,UCeYSnd34IPe57sM8hkjWhrw,FOFeh_vfcD8,NaN,"Me encantan sus babosadas, &quot;Dolores Umbri...","Me encantan sus babosadas, ""Dolores Umbridge"" ...",@LauraE.LedezmaFlores,https://yt3.ggpht.com/-Fh_f0uPKjkyVY5_n_KfFJ5E...,http://www.youtube.com/@LauraE.LedezmaFlores,UCDSYd0Yr7gaxikI7Z2A4hvg,True,none,0,2024-07-17T19:24:59Z,2024-07-17T19:24:59Z,True,0,True,{}
2,UCeYSnd34IPe57sM8hkjWhrw,FOFeh_vfcD8,NaN,Bonjour a Teka desde Québec donde también vine...,Bonjour a Teka desde Québec donde también vine...,@AbrilRodriguez-k2r,https://yt3.ggpht.com/FiXAnRgR05HSFqAzkbZFA3-N...,http://www.youtube.com/@AbrilRodriguez-k2r,UCDSdEL4xwsjXaI-9A5chgmw,True,none,0,2024-07-17T01:45:17Z,2024-07-17T01:45:17Z,True,0,True,{}
3,UCeYSnd34IPe57sM8hkjWhrw,FOFeh_vfcD8,NaN,Weey quitaron los comentarios de spotify!<br>A...,Weey quitaron los comentarios de spotify!\nA m...,@musicodesconocido,https://yt3.ggpht.com/6d9wkRzKT_0h46LyR8D8_i8a...,http://www.youtube.com/@musicodesconocido,UCRV6qG5h6C4PmMn1qtE-Z1Q,True,none,0,2024-07-16T14:56:31Z,2024-07-16T14:56:31Z,True,0,True,{}
4,UCeYSnd34IPe57sM8hkjWhrw,FOFeh_vfcD8,NaN,Weey quitaron los comentarios de spotify!<br>A...,Weey quitaron los comentarios de spotify!\nA m...,@musicodesconocido,https://yt3.ggpht.com/6d9wkRzKT_0h46LyR8D8_i8a...,http://www.youtube.com/@musicodesconocido,UCRV6qG5h6C4PmMn1qtE-Z1Q,True,none,0,2024-07-16T14:56:11Z,2024-07-16T14:56:11Z,True,0,True,{}

In [12]:
df_replies = df[df["replies"] != "{}"]
df_replies

,channelId,videoId,commentId,textDisplay,textOriginal,authorDisplayName,authorProfileImageUrl,authorChannelUrl,authorChannelId,canRate,viewerRating,likeCount,publishedAt,updatedAt,canReply,totalReplyCount,isPublic,replies
16,UCeYSnd34IPe57sM8hkjWhrw,FOFeh_vfcD8,NaN,cómo es que ya no querían a evo si traían tan ...,cómo es que ya no querían a evo si traían tan ...,@zelskidorantestavera3891,https://yt3.ggpht.com/ytc/AIdro_kXvTlnXWtAsHsg...,http://www.youtube.com/@zelskidorantestavera3891,UC5o84xEIK9RAs9G9OHK1fUQ,True,none,0,2024-07-11T05:05:42Z,2024-07-11T05:05:42Z,True,1,True,"{'comments': [{'kind': 'youtube#comment', 'eta..."

In [44]:
(df_replies["replies"])

TypeError: 'module' object is not callable

In [33]:
# Extraer los comentarios
comments_list = df_replies["replies"].apply(lambda x: x['comments'] if isinstance(x, dict) and 'comments' in x else [])

# Crear un DataFrame a partir de la lista de comentarios
comments_df = comments_list.explode().reset_index(drop=True)

# Extraer el texto de los comentarios, si hay comentarios
if not comments_df.empty:
    comments_df = comments_df.apply(lambda x: x['text'] if isinstance(x, dict) and 'text' in x else None)

# Para ver el resultado
print(comments_df)

0    None
Name: replies, dtype: object

In [37]:
json = json.loads(list(df_replies["replies"])[0])
json

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

In [14]:
yt_utils.extract_comments(df_replies["replies"])

[]